services:
  db:
    image: postgres:16
    container_name: job-agent-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: job_agent
    ports:
        - "5432:5432"
    volumes:
        - job_agent_db_data:/var/lib/postgresql/data
volumes:
  job_agent_db_data: